spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/pe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8085

grpc:
  port: 9095
  enable-reflection: true