spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/origination
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: ilya@example.com
    password: 1111
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  port: 8084

origination:
  client:
    scoring:
      grpc:
        host: localhost
        port: 9096

grpc:
  port: 9094
  enable-reflection: true

fixedDelay:
  in:
    milliseconds: 1000
